name: Run Gradle Build on PR

on: pull_request

jobs:
  gradle:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
    - uses: gradle/gradle-build-action@v3
      with:
        arguments: build
